import './globals.css'
import { Inter } from 'next/font/google'
import TopNavDynamic from "@/components/nav/topNav/topNav-dynamic";
import SideNavProfile from "@/components/nav/sideNav/saideNav-profole";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Edu Web',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} data-bs-spy="scroll" data-bs-target=".navbar" data-bs-offset="50">
      <div className="container-fluid bg-dark vh-100 text-light mb-5 pb-5">
          <div className="container mt-5 pt-5">
              <div className="row mt-5 rounded-5 shadow-lg">
                  <div className="col-2">
                      <SideNavProfile/>
                  </div>
                  <div className="col-10">
                      {children}
                  </div>
              </div>
          </div>
      </div>

      </body>
    </html>
  )
}
