import './globals.css'
import './learn-lesson.css'
import { Inter } from 'next/font/google'
import SideNavLesson from "@/components/nav/sideNav/sideNav-Lesson";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Edu Web',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} data-bs-spy="scroll" data-bs-target=".navbar" data-bs-offset="50">
      <div className="container-fluid bg-dark text-light container-fluid_layout">

          <div className="row row_layout">
              <div className="col-2 col_layout">
                  <SideNavLesson/>
              </div>
              <div className="col-10 bg-dark text-white col_layout">
                  {children}
              </div>
          </div>

      </div>

      </body>
    </html>
  )
}
