import './globals.css'
import { Inter } from 'next/font/google'
import ChatBot from "@/components/chatbot/chatbot";
import TopNavDynamic from "@/components/nav/topNav/topNav-dynamic";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Edu Web',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} data-bs-spy="scroll" data-bs-target=".navbar" data-bs-offset="50">
      <div>

          {children}
          <ChatBot/>
      </div>
      </body>
    </html>
  )
}
